#!/bin/bash

# Quick fix for the new server
# Run this to complete the setup

SERVER_IP="108.61.245.179"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Fix New Server Setup                               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Server IP: $SERVER_IP"
echo ""
echo "To complete the setup, you need to:"
echo ""
echo "1. Get the root password from Vultr dashboard:"
echo "   https://my.vultr.com/"
echo "   Click on 'rv2class-frontend' server"
echo "   Look for 'Password' or 'Server Information'"
echo ""
echo "2. SSH into the server:"
echo "   ssh root@$SERVER_IP"
echo ""
echo "3. Check if the app is running:"
echo "   pm2 list"
echo "   pm2 logs rv2class"
echo ""
echo "4. Check Nginx status:"
echo "   systemctl status nginx"
echo "   nginx -t"
echo ""
echo "5. Open firewall if needed:"
echo "   ufw allow 80/tcp"
echo "   ufw allow 443/tcp"
echo "   ufw reload"
echo ""
echo "Or I can help you with the next steps!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "SUMMARY:"
echo "✅ Server created: $SERVER_IP"
echo "✅ App installed and built"
echo "✅ PM2 running"
echo "✅ Nginx configured"
echo "❓ Need to verify access"
echo ""
echo "Quick test: Try opening in browser:"
echo "  http://$SERVER_IP"
echo ""
