version: '3.8'

services:
  deepfilter-agent:
    build:
      context: .
      dockerfile: Dockerfile.deepfilter
    container_name: deepfilter-audio-agent
    restart: unless-stopped
    
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AGENT_IDENTITY=deepfilter-agent
      - POST_GAIN=${POST_GAIN:-1.0}
      - ATTENUATION_LIMIT=${ATTENUATION_LIMIT:-100}
      - LIVEKIT_ROOMS=${LIVEKIT_ROOMS:-}
    
    # Optional: Enable GPU support
    # Uncomment these lines if you have NVIDIA GPU:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Port for health checks
    ports:
      - "8080:8080"
    
    # Shared memory (for PyTorch)
    shm_size: '2gb'
