#!/bin/bash
# Real-time test script

echo "🧪 REAL-TIME AGENT TEST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 INSTRUCTIONS:"
echo ""
echo "1. Open your browser and join a room (any room)"
echo "2. Keep the room open"
echo "3. This script will watch Fly.io logs for 30 seconds"
echo "4. You'll see if the agent detects you and processes your audio"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER when you're IN A ROOM and ready to test..."
echo ""
echo "🔍 Watching Fly.io logs for 30 seconds..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

timeout 30 flyctl logs --app rv2class-audio-agent 2>&1 | grep -E "(Connected|Found.*participants|👋|📢|📡|🎤|🎙️|🔊|Error)" --line-buffered

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Test complete!"
echo ""
echo "🔍 WHAT TO LOOK FOR:"
echo ""
echo "✅ WORKING:"
echo "   📢 Track published - Kind: 1, Participant: YOUR_NAME"
echo "   📡 Subscribing to audio track from: YOUR_NAME"
echo "   🎤 Subscribed to audio from: YOUR_NAME"
echo "   🎙️ Publishing DeepFiltered track: YOUR_NAME_deepfiltered"
echo "   🔊 YOUR_NAME audio level: XX.X"
echo ""
echo "❌ NOT WORKING:"
echo "   📊 Found 0 existing participants"
echo "   (No other messages)"
echo ""
